###
GET http://localhost:8080/categories

###
GET http://localhost:8080/categories/parks

###
GET http://localhost:8080/categories/monuments

###
POST http://localhost:8080/categories
Content-Type: application/json
Authorization: Bearer < your token >

{
  "name": "Category 1",
  "symbol": "C",
  "description": "Category 1 description"
}
